### ISSUE TITLE
Context Preview Section Fluttering

### ISSUE THREAD

**Issue by ayuxy027** [pieces-app/support#238] opened 2024-06-02 13:07 UTC
### Software

Desktop Application

### Operating System / Platform

macOS

### Your Pieces OS Version

Latest

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

When opening the desktop app, the context preview section experienced lag. At the time, the internet connection was unstable. 

Device: MacBook Air with 8 GB of RAM.

Steps:
1. Started the device.
2. Launched the Pieces app.
3. Attempted to connect to the internet; the first attempt failed, but the second attempt was successful.
4. The error then appeared.

https://github.com/pieces-app/support/assets/144288354/082db63f-d5c7-46e9-ba23-6fdb08d7937f

**Comment by mack-at-pieces** [comment] 2024-06-15 16:28
Hi @ayuxy027 - Thank you for sharing this here. When you quit & reopen the desktop app, are you still experiencing this issue?

Thanks!

**Comment by ayuxy027** [comment] 2024-06-15 23:38
> Hi @ayuxy027 - Thank you for sharing this here. When you quit & reopen the desktop app, are you still experiencing this issue?
> 
> Thanks!

Hi @mack,

Thanks for your response. Upon quitting and reopening the desktop app, the issue no longer persists.

**Comment by mack-at-pieces** [comment] 2024-06-16 14:07
Thanks @ayuxy027 - Glad to hear that's the case. If this issue happens again, please let us know and we'll try and identify the cause. Could be related to RAM usage. I'm going to close this issue for now.

**Closed by mack-at-pieces** 2024-06-16 14:07 UTC
Labels: app:desktop application, status:user responded
