### ISSUE TITLE
OneDrive sync issue, x:\path\OneDrive - tenant\Documents\com.pieces.pfd\production\database.lock file in use by pieces_for_x.exe

### ISSUE THREAD

**Issue by johnkennyuk** [pieces-app/support#63] opened 2024-01-25 11:47 UTC
### Software

Desktop Application, Pieces OS

### Operating System

Windows

### Your Pieces OS Version

7.2.6

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

OneDrive sync issue, x:\path\OneDrive - tenant\Documents\com.pieces.pfd\production\database.lock file in use by pieces_for_x.exe

I've read something regarding Pieces OS and OneDrive issues somewhere in the past but am unable to find it again, it was related to OneDrive Sync issue with Pieces OS appdata being a known issue, but I wanted to post the issue here too as I'd be happy to assist if required?

Has anything been worked out yet regarding OneDrive sync issues now the appdata is stored within the users' documents folder and OneDrive Known folder move is enabled??

Thanks

**Comment by rosie-at-pieces** [comment] 2024-01-25 16:05
hi there, all onedrive related issues are being tracked on [this issue ](https://github.com/pieces-app/support/issues/38). please go join the conversation there!

i will be closing this ticket and marking it as a duplicate.

**Comment by rosie-at-pieces** [comment] 2024-01-25 16:05
duplicate of https://github.com/pieces-app/support/issues/38

**Closed as completed** 2024-01-25 16:06 UTC
Labels: duplicate, os:windows, app:desktop application, app:pieces os
