### ISSUE TITLE
Snippets disappeared after update (v 7.2.6)

### ISSUE THREAD

**Issue by RavirajKumarTiwari** [pieces-app/support#54] opened 2024-01-20 13:00 UTC
### Software

Desktop Application, Pieces OS

### Operating System

Windows

### Your Pieces OS Version

7.2.6

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

Updated Pieces OS this morning and was logged out of Pieces Desktop client on Windows 11. After I logged back in, my snippets were gone.
![Screenshot 2024-01-13 031628](https://github.com/pieces-app/support/assets/84895533/64a50ef4-590e-430f-9ea4-34cd7b3f1c5b)

**Comment by rosie-at-pieces** [comment] 2024-01-20 13:28
hi @RavirajKumarTiwari , we want to keep all related 7.2.x issues on the original [ticket](https://github.com/pieces-app/support/issues/38), so i'm going to mark this as a duplicate and close. 

i'll post a response there.

**Comment by rosie-at-pieces** [comment] 2024-01-20 13:28
duplicate of https://github.com/pieces-app/support/issues/38

**Closed** 2024-01-20 13:29 UTC
Labels: duplicate, os:windows, app:desktop application, app:pieces os
