### ISSUE TITLE
"PathNotFoundException" while trying to start Pieces OS

### ISSUE THREAD

**Issue by Grayson-code** [pieces-app/support#158] opened 2024-04-12 10:47 UTC
### Software

Pieces OS

### Operating System

Windows

### Your Pieces OS Version

v8.1.0

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

![image](https://github.com/pieces-app/support/assets/80775046/e5e4ac02-c019-4769-ad82-9cc32cb31106)
I have encountered this error when I tried to install Pieces Suite. I have reinstalled the entire suite and still have encountered this error.

**Comment by Grayson-code** [comment] 2024-04-12 11:36
I'm on Win 10 Pro, 22H2

**Comment by Grayson-code** [comment] 2024-04-12 11:36
Edition	Windows 10 Pro
Version	22H2
OS build	19045.4170
Experience	Windows Feature Experience Pack 1000.19054.1000.0

**Comment by rivlin132** [comment] 2024-04-17 20:15
i got this error

**Comment by lior102** [comment] 2024-04-17 20:16
I got the same error

**Comment by lior102** [comment] 2024-04-18 21:15
Yes, it still happens I tried restarting the computer and it didn't work I also tried deleting and re-downloading I still encountered this problem I would appreciate it if you could check why this is happening

**Comment by mark-at-pieces** [comment] 2024-04-18 21:17
@lior102 would you mind send your exact error?
does the path include "Admin" as well?

**Comment by mark-at-pieces** [comment] 2024-04-18 21:19
also can you double check that you have a 

'com.pieces.os' folder in your

'C:\Users\{YOUR_USER}\Documents'

**Comment by lior102** [comment] 2024-04-18 21:23
> @lior102אכפת לך לשלוח את השגיאה המדויקת שלך? האם הנתיב כולל גם "אדמין"?

![צילום מסך 2024-04-17 202251](https://github.com/pieces-app/support/assets/137498417/4a55796b-791c-4dd4-8322-5aee27aaa7c4)
This is the full message I get: PathNotFoundException: Creation failed, path = 'C:\Users\Admin\Documents\com.pieces.os\production\Pieces\Formats' (OS Error: The system cannot find the file specified. ermo = 2

**Comment by lior102** [comment] 2024-04-18 21:24
> גם אתה יכול לבדוק שוב שיש לך א
> 
> 'com.pieces.os' בתיקייה שלך
> 
> `C:\Users\{YOUR_USER}\Documents`

And yes I have such a folder

**Comment by mark-at-pieces** [comment] 2024-04-18 21:24
Very interesting, if you UserName on this User "Admin" as well where your com.pieces.os folder is located?

**Comment by lior102** [comment] 2024-04-18 21:28
This is where my folder is located
C:\Users\Admin\Documents

**Comment by mark-at-pieces** [comment] 2024-04-18 21:31
I'm thinking this is is permissions related to the user account on your windows machine, is this by any changes a Work computer or a personal device?

Question: have you attempted to run PiecesOS as administrator?(not sure if this even possible)

**Comment by lior102** [comment] 2024-04-18 21:34
I didn't make any changes and I checked that PiecesOS has all the necessary permissions and it still didn't work for me

**Comment by nathan-courtney-pieces** [comment] 2024-04-18 21:35
Do you have this permission enabled within your settings app?

<img width="684" alt="ApplicationFrameHost_k9t9XflMxt" src="https://github.com/pieces-app/support/assets/46496645/38937e0a-764c-4593-82bf-36b12bb77dc4">

**Comment by nathan-courtney-pieces** [comment] 2024-04-18 21:47
Interesting... Within the com.pieces.os folder, do you see any files within com.pieces.os\production\Pieces or do you have a bunch of directories with no files in them?

**Comment by mark-at-pieces** [comment] 2024-04-18 21:48
would you mind ziping up the com.pieces.os directory and sending us a copy to nathan@pieces.app and mark@pieces.app?

**Comment by lior102** [comment] 2024-04-18 21:49
![Screenshot 2024-04-19 004852](https://github.com/pieces-app/support/assets/137498417/e1ae6514-cc0b-444c-9fa9-d20ccd902607)


> מעניין... בתוך התיקיה com.pieces.os, האם אתה רואה קבצים כלשהם בתוך com.pieces.os\production\Pieces או שיש לך חבורה של ספריות ללא קבצים?

**Comment by lior102** [comment] 2024-04-18 21:50
> האם אכפת לך לדחוס את ספריית com.pieces.os ולשלוח לנו עותק אל [nathan@pieces.app](mailto:nathan@pieces.app) ו- [mark@pieces.app](mailto:mark@pieces.app) ?

I'll send just a moment

**Comment by lior102** [comment] 2024-04-18 21:51
I sent you both

**Comment by nathan-courtney-pieces** [comment] 2024-04-18 21:52
After you send that over, try deleting the entire com.pieces.os folder, and then relaunch Pieces OS. you may have to kill Pieces OS in task manager if it is already running

**Comment by lior102** [comment] 2024-04-18 21:55
> After you send that over, try deleting the entire com.pieces.os folder, and then relaunch Pieces OS. you may have to kill Pieces OS in task manager if it is already running

I tried now the same error happened

**Comment by nathan-courtney-pieces** [comment] 2024-04-18 21:56
Actually i should clarify, close down the Pieces Suite installer, delete the com.pieces.os folder, do not repopen the Pieces Suite Installer, and launch Pieces OS from navigating to the list of applications on your machine and click the Pieces OS icon to launch it

**Comment by nathan-courtney-pieces** [comment] 2024-04-18 22:02
@lior102 Are you syncing your Documents folder with OneDrive or are you using OneDrive at all?

**Comment by lior102** [comment] 2024-04-18 22:03
@nathan-courtney-pieces I don't use OneDrive

**Comment by nathan-courtney-pieces** [comment] 2024-04-18 22:07
@lior102 Could you right-click your Documents folder and select "Properties" from the menu list and send a screenshot? 

You should see something like this: 
<img width="273" alt="explorer_V2S8tGDdC0" src="https://github.com/pieces-app/support/assets/46496645/270b1ffa-89dd-49e6-ad88-0366b3c8a4b7">

Wouldn't hurt to send a screenshot of the security tab as well  with your user account selected (or what you are signed in with) 
<img width="273" alt="explorer_r7UGQmCuqy" src="https://github.com/pieces-app/support/assets/46496645/4181ad28-e26a-40f5-9b1d-d5b690916988">

**Comment by lior102** [comment] 2024-04-18 22:09
![image](https://github.com/pieces-app/support/assets/137498417/599eac12-9b0f-4169-8e95-75bd3961a65a)
![image](https://github.com/pieces-app/support/assets/137498417/a07c9604-7529-4065-8d5f-b4effb51fa8e)

**Comment by nathan-courtney-pieces** [comment] 2024-04-18 22:16
@lior102 Thanks for sending that over. What I find odd is that your username is "lior" but your file path is **\Users\Admin** for your user directory. Do you know why that is? Do you have a directory on your machine at **\Users\lior** ?

**Comment by lior102** [comment] 2024-04-18 22:18
@nathan-courtney-pieces No, I don't have such a library

**Comment by mark-at-pieces** [comment] 2024-04-18 22:31
nathan is trying to reproduce this in a VM rn

**Comment by lior102** [comment] 2024-04-18 22:34
@mark-at-pieces Okay, let us know that there is an answer

**Comment by mark-at-pieces** [comment] 2024-04-18 22:36
we are going to get to the bottom of this

**Comment by nathan-courtney-pieces** [comment] 2024-04-18 22:46
@lior102 , Can you send over screenshots of the the Documents "properties" window of the other two accounts on your securities tab? 

You sent over one of them by highlighting "SYSTEM". I'd like to see what these two are saying 
<img width="323" alt="chrome_iLXM4WNRnN" src="https://github.com/pieces-app/support/assets/46496645/d7367ebd-d6ef-4137-9015-539bd2bb76c9">

**Comment by mark-at-pieces** [comment] 2024-04-18 23:09
hey @lior102 Nathan and I are still looking into this however might be easier if we could hop on a chat would you mind scheduling some time on my calendar and we will get you booted up, and then post the final solution in here so we can ensure that no one has this issue again!

https://calendar.app.google/FKCAdBW6VSuCoTN67

**Comment by lior102** [comment] 2024-04-19 10:16
@nathan-courtney-pieces 
![image](https://github.com/pieces-app/support/assets/137498417/de3c07da-4ab5-4636-ba8d-e8a0e577fea8)
![image](https://github.com/pieces-app/support/assets/137498417/52e351b3-b5d7-4fe0-b7db-769e83db6574)

**Comment by lior102** [comment] 2024-04-19 10:17
@mark-at-pieces Yes, I made an appointment for today

**Comment by mark-at-pieces** [comment] 2024-04-19 13:28
We found the solution: will be putting an extensive write up in here within the next couple of hours.

Basically Windows defender was blocking our app(s)

Both PiecesOS && PiecesDesktop from writing to the FileSystem

here are a couple screen shots and be sure to allow for this (will also need to do this for both pieces_for_x.exe as well as for os_server.exe

<img width="722" alt="Screenshot 2024-04-19 at 9 12 59 AM" src="https://github.com/pieces-app/support/assets/46659689/5d2309bf-8eb5-49b0-a466-35bfbc6f1a2b">

**Comment by mark-at-pieces** [comment] 2024-04-19 13:29
Note: if you click into

"Controlled folder access setting"

then "allowed application"

you will need to ensure that both PiecesOS and PiecesDesktop are allowed

<img width="488" alt="Screenshot 2024-04-19 at 9 17 09 AM" src="https://github.com/pieces-app/support/assets/46659689/95f2d5a7-3b07-4ea6-8339-3c4ee7525721">

**Comment by mason-at-pieces** [comment] 2024-04-19 19:37
This issue is stale because 3 days has passed with no response from the author. Remove the stale label or have the author comment or else this issue will be closed in 4 days from today.

**Comment by mark-at-pieces** [comment] 2024-04-19 19:39
still an ongoing issue: solution is posted above.

we will have better write up here, as well as a long term solution for this issue here shortly

**Comment by mason-at-pieces** [comment] 2024-04-19 19:44
This issue is stale because 3 days has passed with no response from the author. Remove the stale label or have the author comment or else this issue will be closed in 4 days from today.

**Comment by mason-at-pieces** [comment] 2024-04-19 20:07
> still an ongoing issue: solution is posted above.

Yes, sorry. Was a mistake on my part but has been corrected 👍

**Comment by nathan-courtney-pieces** [comment] 2024-04-19 21:48
We believe we have a solution for this and it will be going out in the next update

**Comment by Grayson-code** [comment] 2024-04-20 06:50
Thanks for the support. The temporary solution has worked. 
IG let the issue stay open till this is resolved permanently.

**Comment by Grayson-code** [comment] 2024-04-20 06:51
Thank you to @rivlin132 and @lior102 for your cooperation.

**Comment by xperiandri** [comment] 2024-04-20 15:25
After I went to the Defender history [as above](https://github.com/pieces-app/support/issues/158#issuecomment-2066587758) and allowed `pieces_for_x.exe` access. Now it works

**Comment by mark-at-pieces** [comment] 2024-04-24 22:05
hey super solid thanks all for the help!

we have added some additional in app messaging (in the case of a failure) pointing to this specific solution.

In the mean time, we continue looking for a better long term solution.

Thanks again for all the help here!

Cheers 🍻

&& Happy Coding!

**Comment by mark-at-pieces** [comment] 2024-04-26 17:45
9.0.2 with ^^ these changes is now live

**Comment by jimbobbennett** [comment] 2024-11-08 02:22
Closing as the changes to help resolve this are now live.

**Closed by jimbobbennett** 2024-11-08 02:22 UTC
Labels: os:windows, app:pieces os, ongoing
