### ISSUE TITLE
Issue with Copilot Conversations Disappearing in VSCode Plugin

### ISSUE THREAD

**Issue by sunarkadeep** [pieces-app/support#123] opened 2024-03-13 04:39 UTC
### Software

VS Code

### Operating System

Windows

### Your Pieces OS Version

v8.0.0

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

so I faced an issue with my vscode plugin....to set the context of this....

so I selected a snippet and clicked Ctrl+Shift+A (which is shortcut for ask copilot within vscode), the pieces copilot side panel opened, it also showed the copilot's response while the answer is being generated like 'Let's see what I got here','Almost there' etc etc...but then suddenly the response from copilot disappeared like I can just see my code and the query I wrote..also like I can access other older chats within vscode but nothing happens when I click on this current chat from copilot home page in vscode side panel via 'select conversation'.....now if I go to pieces desktop app I can also see the same thing....like there's no response from the copilot...only when I click on refresh it shows back....now back to vscode...I have to restart my vscode and then only I can access this copilot chat as in it became 'older chats' and hence is accessible then...but the problem is with live chats...where I ain't getting a response from copilot unless I restart vscode or refresh the chat from pieces desktop

**Comment by caleb-at-pieces** [comment] 2024-03-13 13:58
It sounds like this is related to https://github.com/pieces-app/support/issues/122

**Comment by sunarkadeep** [comment] 2024-03-13 15:10
> It sounds like this is related to #122

oh yes...its the same problem I am facing...so I tried out your suggestions posted there....
so I just have to refresh the copilot chat from desktop app and then I can access it within the vscode...also the follow-up Questions in that chat works exactly fine within vscode just like normal...so the problem is just with the first time response from the copilot...
also I am only using cloud models and its the same for all...I don't have any on-device model...

**Comment by rosie-at-pieces** [comment] 2024-03-13 17:52
closing this as a duplicate, please continue the conversation on #122

**Comment by rosie-at-pieces** [comment] 2024-03-13 17:53
duplicate of #122

**Closed by rosie-at-pieces** 2024-03-13 17:52 UTC
Labels: os:windows, status:needs triage, app:vs code
