### ISSUE TITLE
Jetbrains IDEs cant connect to Pieces OS

### ISSUE THREAD

**Issue by Farhan-Nahiyan** [pieces-app/support#384] opened 2024-08-29 13:55 UTC
### Software

Pieces OS, JetBrains

### Operating System / Platform

Windows

### Your Pieces OS Version

10.14

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

Pycharm and IntelliJ can't connect to Pieces OS and copilot also doesn't work
IDE version: 2024.1.6
Extension version: 9.0.2

![image](https://github.com/user-attachments/assets/b4a9308d-5ed1-4016-9fc6-dd6d30409aec)
![image](https://github.com/user-attachments/assets/a2b2f17e-9560-4ade-b152-bf54e485e5f6)

**Comment by caleb-at-pieces** [comment] 2024-08-30 14:49
Hey @Farhan-Nahiyan thanks for reaching out to us about these issues.

Can you please open 'http://localhost:1000/.well-known/health' in your browser with Pieces OS running? It should say 'ok'.

Besides that could you send me some more information that may lead us to see the root cause of this issue?
- Please send me your logs, they are present within your documents folder: Documents\com.pieces.os\production\Support\logs
- What version of windows are you running?
- Are you on an insider build of windows?

It would be great if we could hop on a call together to do a live debugging session, this will likely result in the fastest resolution. Pick a time that works for you here on my calendar: https://calendar.app.google/acGZTAS7QL8fLhZo8

**Comment by Farhan-Nahiyan** [comment] 2024-08-31 15:25
Alright, my windows version is 22H2 and build is 19045.4780. I'm not on the
insider program. logs provided are from the days where i experienced the
issue. And the issue seems to be fixed in Pieces OS 10.1.5

**Comment by mack-at-pieces** [comment] 2024-09-03 16:52
Hey @Farhan-Nahiyan last week we released updates to Pieces OS, Pieces Desktop, and our JetBrains plugin to introduce better support for the latest JetBrains IDE versions. It seems this has resolved your issue, but if you continue to experience any other problems don't hesitate to let us know! I'm going to close this issue for now. Thanks!

**Closed by mack-at-pieces** 2024-09-03 16:52 UTC
Labels: app:jetbrains, app:pieces os
