### ISSUE TITLE
Ai is giving late replays also taking my 50% of my cpu 

### ISSUE THREAD

**Issue by cybersleuth0** [pieces-app/support#352] opened 2024-08-09 14:29 UTC
### Software

Pieces OS

### Operating System / Platform

Windows

### Your Pieces OS Version

10.0.3

### Early Access Program

- [X] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

![Screenshot 2024-08-08 154102](https://github.com/user-attachments/assets/d5521de4-e632-4206-bc19-eafbfe4ab2e8)

check out this video

https://drive.google.com/file/d/1qaHK71caXoVRxFbkbj4ofO4K37SP7Xso/view?usp=sharing

**Comment by rosie-at-pieces** [comment] 2024-08-09 14:33
@cybersleuth0 can you please let me know what LLM you are using when you experience this? Is it a local model like Mistral or a cloud model like GPT 4?

**Comment by cybersleuth0** [comment] 2024-08-10 13:53
yes its a cloud model GPT4

**Comment by rosie-at-pieces** [comment] 2024-08-12 12:45
Ok thanks for letting me know - this is likely the same issue as #351 . please refer to this issue and see @mark-at-pieces response

**Comment by rosie-at-pieces** [comment] 2024-08-12 12:46
Duplicate of #351

**Closed by rosie-at-pieces** 2024-08-12 12:46 UTC
Labels: app:pieces os
