### ISSUE TITLE
I'am sorry Something went wrong with processing. please wait a few seconds and try again or contact support@pieces.app

### ISSUE THREAD

**Issue by Kiran-Jadhav200** [pieces-app/support#500] opened 2024-12-07 06:07 UTC
### Software

Desktop Application

### Operating System / Platform

Windows

### Your Pieces OS Version

10.1.15

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

the ChatGpt does not work but with other Gemini works I had faced this before also after trying different solutions  I formatted my laptop by installing new windows, and it worked for 4 days after that, with the same issue please fix this issue. end semester exams are near we need ChatGPT

yes Gemini works but it sucks ChatGPT is best 

 **please fix this issue**

Thank You 
### pieces information
![Image](https://github.com/user-attachments/assets/e95be432-efd0-42e6-b789-2aac6b6dab35)

### The Bug/ issue
![Image](https://github.com/user-attachments/assets/49aa784e-24b1-46dc-b182-a7d3484ba42b)

**Comment by hra42** [comment] 2024-12-07 08:40
this look like a duplicate of #471.

@Kiran-Jadhav200 Could you please do the following:
Paste this request in your browser 'http://localhost:1000/applications' while your PiecesOS is running
note: port is 1000 for windows/macos, and 5323 for linux
send the result to mark@pieces.app

He will take a look at this and tell you how to move forward.

**Comment by mark-at-pieces** [comment] 2024-12-09 14:37
closing for now as this is a duplicate

**Closed by mark-at-pieces** 2024-12-09 14:37 UTC
Labels: os:windows, status:needs triage, app:desktop application, status:ongoing
