### ISSUE TITLE
Something went wrong with processing

### ISSUE THREAD

**Issue by AndreyPLtn** [pieces-app/support#503] opened 2024-12-07 14:43 UTC
### Software

Desktop Application, Pieces OS

### Operating System / Platform

Windows

### Your Pieces OS Version

Pieces OS 10.1.15

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

Any answer gives an error. This problem is the second day.
![Image](https://github.com/user-attachments/assets/e237c726-ab1e-4c81-9c2e-706b2aee0675)

**Comment by mark-at-pieces** [comment] 2024-12-09 14:40
Hey @AndreyPLtn  thank you for reaching out to support.

I believe this is a duplicate of

https://github.com/pieces-app/support/issues/471

Please take a look at this ticket for next steps.

**Closed by mark-at-pieces** 2024-12-09 14:40 UTC
Labels: os:windows, app:desktop application, app:pieces os
