### ISSUE TITLE
Pieces Desktop App - Lost Connection to PiecesOS

### ISSUE THREAD

**Issue by ShauryaKesarwani** [pieces-app/support#542] opened 2024-12-19 19:22 UTC
_PiecesOS Information_

**ID:** 52cc1900-6d58-4b9d-8da9-88d36e124b14
**User:** 61095a0d-c770-4dbb-b74a-1ecbe495e84d
**Current Version:** Unknown
**Min Version Supported:** 11.0.0
**Max Version Supported:** 12.0.0
**Local Port:** 127.0.0.1:39300

_Device Information_

**Operating System:** Windows
**Current Version:** "Windows 10 Home Single Language" 10.0 (Build 26100)
**Min Version Supported:** Windows 10 Build 1903

When adding folder, tried on both claude 3.5 and gpt 4o (cloud), pieces OS is crashing (lost connection to PiecesOS screen is shown)
Adding specific file does work though.

**Comment by mark-at-pieces** [comment] 2024-12-19 20:06
duplicate of https://github.com/pieces-app/support/issues/536

going to close for now, this looks to be the build of windows that is affected, we are actively looking into this issue at the moment

**Closed by mark-at-pieces** 2024-12-19 20:06 UTC
Labels: bug, os:windows, status:new, app:desktop application, app:pieces os
