### ISSUE TITLE
Pieces os wont start after update

### ISSUE THREAD

**Issue by abhijitWebDev** [pieces-app/support#364] opened 2024-08-15 11:56 UTC
### Software

Pieces OS

### Operating System / Platform

Windows

### Your Pieces OS Version

10.10

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

The pieces OS is stuck in a loading state.
![image](https://github.com/user-attachments/assets/59c1f40e-e81c-4258-a42d-285e608d848b)

**Comment by mark-at-pieces** [comment] 2024-08-15 12:39
this is a duplicate of this ticket issue #363, please follow along there, will be closing for now

**Closed by mark-at-pieces** 2024-08-15 12:39 UTC
Labels: duplicate, app:pieces os

**Comment by mark-at-pieces** [comment] 2024-08-15 13:29
Note: will be fixed in 10.1.1, thank you for reaching out(release will be live in an hour)
