### ISSUE TITLE
After update pieces os is not working.

### ISSUE THREAD

**Issue by Alfazal007** [pieces-app/support#37] opened 2024-01-14 05:19 UTC
### Software

Desktop Application

### Operating System

Windows

After updating to latest version I just lost all the saved snippets and pieces stopped working tried to reinstall it but same issue.
Getting this after few minutes, 
![Screenshot 2024-01-14 020126](https://github.com/pieces-app/support/assets/109091069/d096e532-5c8b-477a-b2d3-d71c91e9dbd6)

**Comment by rosie-at-pieces** [comment] 2024-01-15 13:56
Hi there, this problem is already being tracked on a different issue, please refer to https://github.com/pieces-app/support/issues/38.

**Comment by rosie-at-pieces** [comment] 2024-01-15 13:56
Duplicate of https://github.com/pieces-app/support/issues/38

**Closed** 2024-01-15 13:57 UTC
Labels: duplicate
