### ISSUE TITLE
i'm sorry something went wrong with the processing

### ISSUE THREAD

**Issue by azathoth-69** [pieces-app/support#483] opened 2024-11-28 15:16 UTC
### Software

Desktop Application, Pieces OS

### Operating System / Platform

Windows

### Your Pieces OS Version

3.2.4, 10.1.15

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

any thing i type get this response "i'm sorry something went wrong with the processing" i have tried all the llm's but still get the same response . please fix this

**Comment by hra42** [comment] 2024-11-28 22:46
I think this might be a duplicate of #471

**Comment by Kiran-Jadhav200** [comment] 2024-11-29 05:03
facing same issue I have reinstalled the pieces but still facing this issue and also hard reset 

![Image](https://github.com/user-attachments/assets/df3add21-e9d4-4e63-8506-d7df01cd918d)

**Comment by hra42** [comment] 2024-11-29 14:52
@Kiran-Jadhav200 Please look at issue #471

**Comment by mark-at-pieces** [comment] 2024-11-29 15:41
Thank you @hra42 

This is looking like a duplicate of this 

https://github.com/pieces-app/support/issues/471

please feel free to add a meeting on my [calendar](https://calendar.app.google/ni3AT78qchHkuZzd8) or reach out at mark@pieces.app

closing for now.

**Closed by mark-at-pieces** 2024-11-29 15:41 UTC
Labels: status:needs triage, app:desktop application, app:pieces os
