### ISSUE TITLE
Pieces OS and Pieces For Developers display a blank screen

### ISSUE THREAD

**Issue by skamansam** [pieces-app/support#69] opened 2024-01-29 16:57 UTC
### Software

Pieces OS

### Operating System

Linux

### Your Pieces OS Version

7.2.7

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

When running the pieces-os snap and/or the pieces-for-developers snap, only a blank screen is visible. Nothing else happens and nothing is shown in the window (see screenshots below). Even after running `snap remove --purge pieces-os`, and reinstalling, the same is shown. I am on Fedora 39, all packages up to date as of January 29th, 2024. Here is my system info:

# System Details Report
---

## Report details
- **Date generated:**                              2024-01-29 10:33:27

## Hardware Information:
- **Hardware Model:**                              ASRock Z77 Extreme4
- **Memory:**                                      32.0 GiB
- **Processor:**                                   Intel® Core™ i7-3770K × 8
- **Graphics:**                                    Intel® HD Graphics 4000 (IVB GT2)
- **Disk Capacity:**                               5.7 TB

## Software Information:
- **Firmware Version:**                            P2.90
- **OS Name:**                                     Fedora Linux 39 (Workstation Edition)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               45.2
- **Windowing System:**                            X11
- **Kernel Version:**                              Linux 6.6.9-200.fc39.x86_64

![image](https://github.com/pieces-app/support/assets/102971/cd3de86d-db27-4abb-8caa-0c96abcecacc)

![image](https://github.com/pieces-app/support/assets/102971/2968dfff-7a38-444d-91dc-cb8ffbcd1bcd)

**Comment by rosie-at-pieces** [comment] 2024-01-29 17:41
hey @skamansam this looks like [this issue](https://github.com/pieces-app/support/issues/10). can you please take a look at that ticket?

I'm going to close this ticket as a duplicate.

**Comment by rosie-at-pieces** [comment] 2024-01-29 17:41
duplicate of https://github.com/pieces-app/support/issues/10

**Closed** 2024-01-29 17:42 UTC
Labels: duplicate, os:Linux, app:pieces os

**Comment by skamansam** [comment] 2024-02-05 16:37
Yes, this is a duplicate. thank you, @rosie-at-pieces !
