### ISSUE TITLE
Pieces Desktop App - Lost Connection to PiecesOS

### ISSUE THREAD

**Issue by rafael-a-g-n** [pieces-app/support#541] opened 2024-12-19 17:00 UTC
_PiecesOS Information_

**ID:** 18986c5c-5aef-40f4-ac00-93da40fd8b47
**User:** 1446bb64-5370-4644-a0ee-5ab3b4f3a7ac
**Current Version:** Unknown
**Min Version Supported:** 11.0.0
**Max Version Supported:** 12.0.0
**Local Port:** 127.0.0.1:39300

_Device Information_

**Operating System:** Windows
**Current Version:** "Windows 10 Pro" 10.0 (Build 26100)
**Min Version Supported:** Windows 10 Build 1903

**Comment by mark-at-pieces** [comment] 2024-12-19 17:02
Hey @rafael-a-g-n could you provide some steps to reproduce?

as well were you adding a folder as context to the copilot that causes this issue? or something different

**Comment by mark-at-pieces** [comment] 2024-12-19 18:24
This appears to be a duplicate of this ticket

https://github.com/pieces-app/support/issues/541

closing this issue to consolidate these

**Closed by mark-at-pieces** 2024-12-19 18:24 UTC
Labels: bug, os:windows, status:new, app:desktop application, app:pieces os
