### ISSUE TITLE
Copilot cloud LLM not working even if I updated to 10.1.12

### ISSUE THREAD

**Issue by Codeeyyy** [pieces-app/support#445] opened 2024-11-07 04:32 UTC
### Software

Pieces OS

### Operating System / Platform

Windows

### Your Pieces OS Version

10.1.12

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

I was normally chatting with copilot when this issue raised . Copilot is taking years for a response and most of the time I'm sorry . Something went wrong. I then noticed that I have to update the OS when I did the same issue was there . I restarted my PC , OS and did hard time reset but nothing happened

**Comment by sami2019** [comment] 2024-11-07 05:12
Its same for me as well after updating the pieces os its not working 

<img width="691" alt="Screenshot 2024-11-07 at 1 11 28 PM" src="https://github.com/user-attachments/assets/76b8b78d-5f97-4e86-bbd4-337a4d59be47">

**Comment by KaiSouth** [comment] 2024-11-07 05:39
same for me
![image](https://github.com/user-attachments/assets/50b8d7bf-3ff7-48e4-b06b-e4e280fbbe56)

**Comment by tsavo-at-pieces** [comment] 2024-11-07 06:59
Hey @KaiSouth @sami2019 and @Codeeyyy we're actively working on resolving a malicious attack likely from a sovereign entity outside of the US trying to gain access to AI Capabilities and Models available here in the US. 

If you could, we just rolled out an update. Restart PiecesOS and the Desktop app and report back. 

It would be incredibly helpful. 

We're working on this around the clock and hope to have everything resolved by the end of the week.

**Comment by tsavo-at-pieces** [comment] 2024-11-07 07:00
related to #444

**Comment by rutvik-at-pieces** [comment] 2024-11-22 07:11
Closing this issue as the mentioned cloud LLM issues seems to have been fixed in the recent POS and product releases shipped in the last two weeks. 

@Codeeyyy @sami2019 @KaiSouth Please update to the latest POS build which is `10.1.13` atm and update the respective products to their latest versions as well to confirm the issue is fixed. Feel free to re-open the issue if that's not the case and if you've any other details to share on the issue.

**Closed by rutvik-at-pieces** 2024-11-22 07:11 UTC
Labels: app:pieces os
