### ISSUE TITLE
Message exceeded the context limit for claude LLM Issue

### ISSUE THREAD

**Issue by dhruv465** [pieces-app/support#508] opened 2024-12-11 07:33 UTC
### Software

Desktop Application

### Operating System / Platform

Linux

### Your Pieces OS Version

Pieces OS 10.1.15

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

![Image](https://github.com/user-attachments/assets/262696c2-c641-4337-9966-abdc4fb18739)
I'm getting this error every time I try to use the Claude LLM. What's the problem?

**Comment by mark-at-pieces** [comment] 2024-12-11 12:39
This is a duplicate of https://github.com/pieces-app/support/issues/487

So I am going to close this for now.

This issue should be resolved in the next release(coming out late this week or early next week)

**Closed by mark-at-pieces** 2024-12-11 12:39 UTC
Labels: status:needs triage, app:desktop application, os:linux
