### ISSUE TITLE
Unable to resize my pieces app

### ISSUE THREAD

**Issue by ShashankKanaujia** [pieces-app/support#470] opened 2024-11-21 15:23 UTC
### Software

Desktop Application

### Operating System / Platform

macOS

### Your Pieces OS Version

3.2.2

### Early Access Program

- [x] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

i am unable to resize the pieces app on my mac . i downloaded the app through link as it is not available on app store . i performend many ways to resize and called apple care for this and they have done troubleshooting from their after all that nothing has happend then they said that is from developer end . 

please resolve this problem as soon as possible so i can use peices app smoothly .

**Comment by hra42** [comment] 2024-11-22 02:32
Hey @ShashankKanaujia 

Could you check if this is a duplicate of #463 ? From your description I would guess you have the same problem with the onboarding?

**Comment by mack-at-pieces** [comment] 2024-11-22 02:36
Thanks for jumping in here @hra42 . Could very well be a duplicate. Very interesting issue.. I'm curious to learn the version of macOS you are both using. @ShashankKanaujia

**Comment by hra42** [comment] 2024-11-22 03:16
@mack-at-pieces at the time of the issue I was using 15.1, the latest version of macOS.

**Comment by mack-at-pieces** [comment] 2024-11-22 22:12
@hra42 @ShashankKanaujia We have the window size intentionally locked during onboarding, which is what prevents you from resizing, however it should always display at the default window size. I wasn't able to reproduce the extra-large window on my current version of macOS, so I'll have to update and try again there.

Regardless, I do think we can get rid of the lock on the window size during onboarding as it's no longer needed with the latest changes to the layout.

Stay tuned for this in an upcoming desktop app patch 👍🏼

**Comment by ShashankKanaujia** [comment] 2024-11-24 16:04
Yes i have same problem and my mac Os is 15.1.1Sent from my iPhoneOn 22 Nov 2024, at 8:02 AM, Henry Rausch ***@***.***> wrote:﻿
Hey @ShashankKanaujia
Could you check if this is a duplicate of #463 ? From your description I would guess you have the same problem with the onboarding?

**Comment by mack-at-pieces** [comment] 2024-12-19 20:02
Hey @ShashankKanaujia - This will be updated in a patch release today (3.3.1). I'll keep this issue updated #504 as updates continue to unfold.

**Closed by mack-at-pieces** 2024-12-19 20:02 UTC
Labels: on the roadmap, app:desktop application

**Comment by ShashankKanaujia** [comment] 2024-12-19 20:06
As i will see the issue got resolved i will confirm you . Sent from my iPhoneOn 20 Dec 2024, at 1:32 AM, Mack Myers ***@***.***> wrote:﻿
Hey @ShashankKanaujia - This will be updated in a patch release today (3.3.1). I'll keep this issue updated #504 as updates continue to unfold.

**Comment by ShashankKanaujia** [comment] 2024-12-21 18:10
Thank you very much pieces app support …i am very happy and eager to learn from peices . Thanks again . 😊😊Sent from my iPhoneOn 20 Dec 2024, at 1:36 AM, Shashank Kanojia ***@***.***> wrote:﻿As i will see the issue got resolved i will confirm you . Sent from my iPhoneOn 20 Dec 2024, at 1:32 AM, Mack Myers ***@***.***> wrote:﻿
Hey @ShashankKanaujia - This will be updated in a patch release today (3.3.1). I'll keep this issue updated #504 as updates continue to unfold.
