### ISSUE TITLE
Workstream Power Engine

### ISSUE THREAD

**Issue by Viverun** [pieces-app/support#429] opened 2024-10-18 11:31 UTC
### Software

Pieces OS

### Operating System / Platform

Windows

### Your Pieces OS Version

10.1.10

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

I am not able to enable workstream power engine and thus not able to make any use of pieces

**Comment by mack-at-pieces** [comment] 2024-10-21 13:33
Hi @Viverun - This is a duplicate of #426. The team has identified the root cause of the issue and will have a patch out within the next week or so. We appreciate your patience as we identify and resolve the issue. Please see the original GitHub issues for future updates. Thanks so much.

**Closed by mack-at-pieces** 2024-10-21 13:33 UTC
Labels: status:needs triage, app:pieces os
