### ISSUE TITLE
"Indexing your content...." message comes up consistently in PhpStorm when adding a folder as context

### ISSUE THREAD

**Issue by rosie-at-pieces** [pieces-app/support#273] opened 2024-06-26 16:02 UTC
### Software

JetBrains

### Operating System / Platform

Linux

### Your Pieces OS Version

9.0.7

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

![image](https://github.com/pieces-app/support/assets/152189388/61dbd4dd-20ba-4ff5-b6f3-bb762b904b6d)

[Project added as context](https://github.com/Idrinth/mini-mindmap)

Behavior:

- Used GPT 4 for all use cases 
- Linux machine - 20 CPUs, 32 gb
    - Indexing issue happened on PhpStorm, same issue on WebStorm
    - Tried same on desktop app, crashed Pieces OS (spiked over 60% CPU before crash)
- Windows machine - over 100gb RAM
    - PhpStorm issue happened again
    - Crashed Pieces OS again
    - Tried with Mistral
        - Didn’t find the specific info he was looking for, gave general info - 3 different tools that are partially related and could be routing related BUT didn’t crash it

**Comment by sam-at-pieces** [comment] 2024-06-26 16:06
@Dom-Pieces @leonie-at-pieces @brian-pieces could you see if you can reproduce this on Linux?

**Comment by Idrinth** [comment] 2024-06-26 16:13
One sidenote, make sure to composer install the dependencies - if I'm correct with my suspicion the size of vendor folder may be the issue

**Comment by sam-at-pieces** [comment] 2024-06-27 13:18
Thanks for you patience @Idrinth. We are still looking into this. We are still having trouble reproducing this one, our current theory is that it may be an issue particularly with phpstorm or with  running the composer as you suggest.

**Comment by sam-at-pieces** [comment] 2024-06-27 14:41
We still can't reproduce this, neither on windows nor linux. I suspect there is some conflict happening locally or some issue with the install. Would you be available for a quick chat with one of our infrastructure engineers on Monday @Idrinth ? The two people I think that would be most useful in resolving this are OOO until the end of the week.

**Comment by Idrinth** [comment] 2024-06-27 16:01
> We still can't reproduce this, neither on windows nor linux. I suspect there is some conflict happening locally or some issue with the install. Would you be available for a quick chat with one of our infrastructure engineers on Monday @Idrinth ? The two people I think that would be most useful in resolving this are OOO until the end of the week.

I'd be happy to help - drop me a line on discord or x with the time and I'll make sure I'm available

**Comment by caleb-at-pieces** [comment] 2024-08-30 18:45
No longer applicable.

**Closed** 2024-08-30 18:45 UTC
Labels: app:jetbrains
