### ISSUE TITLE
Error Encountered with Pieces App - "Something went wrong with processing"

### ISSUE THREAD

**Issue by rohanrathi99** [pieces-app/support#484] opened 2024-11-29 06:20 UTC
### Software

Desktop Application

### Operating System / Platform

macOS

### Your Pieces OS Version

Installed v10.1.15

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

**Description:**
I have tried using Pieces multiple times (approximately 10 to 15 attempts) and experimented with different prompts, including detailed ones. Unfortunately, every attempt results in the same error message:

"I'm sorry. Something went wrong with processing. Please wait a few seconds and try again, or contact support@pieces.app."

I need clarification on whether this is a known issue with the application. Is there a fix available for this? If not, should I consider removing Pieces from my system?

**Steps to Reproduce:**

- Open Pieces.
- Enter prompts.
- Encounter the above error consistently.
- Expected Behavior:
- The app should process the prompts without errors.

Questions

1. Is this a known issue, or is it specific to my setup?
2. Can I expect a fix for this, or should I consider removing Pieces from my system?

Actual Behavior:

1. The app displays the mentioned error message every time.
2. I would appreciate any guidance or fixes regarding this issue.

Related Images:
![Image](https://github.com/user-attachments/assets/b0113795-2c52-46a0-b79b-77215495bf6f)

**Comment by mark-at-pieces** [comment] 2024-11-29 15:42
This is looking like a duplicate of this 

https://github.com/pieces-app/support/issues/471

please feel free to add a meeting on my [calendar](https://calendar.app.google/ni3AT78qchHkuZzd8) or reach out at mark@pieces.app

closing for now.

**Closed by mark-at-pieces** 2024-11-29 15:42 UTC
Labels: status:needs triage, app:desktop application
