### ISSUE TITLE
I can't use any GPT models other than 'GPT-4o Mini'

### ISSUE THREAD

**Issue by int80x0** [pieces-app/support#528] opened 2024-12-16 23:12 UTC
### Software

Desktop Application, JetBrains, Pieces OS

### Operating System / Platform

Windows

### Your Pieces OS Version

10.1.15

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

"I'm sorry. Something went wrong with processing. Please wait a few seconds and try again, or contact support@pieces.app"

If the model is 4o Mini, everything works fine.

**Comment by mark-at-pieces** [comment] 2024-12-17 22:02
Hey @int80x0, This is a common issue that should be resolve w/ PiecesOS 11.0.0:
1. either a rate limiting problem(that is resolved if you authenticate)
or
2. some other issus within the conversation flow.

if this is NOT resolved after authenticating and on PiecesOS please schedule some time with us on my [calendar](https://calendar.app.google/knJSkkMhFomcQMcs7)

**Comment by mark-at-pieces** [comment] 2024-12-17 22:03
Duplicate of https://github.com/pieces-app/support/issues/471

**Comment by mark-at-pieces** [comment] 2024-12-17 22:03
going to close for now please review this previous issue!

**Closed by mark-at-pieces** 2024-12-17 22:03 UTC
Labels: bug, os:windows, status:new, app:desktop application, app:jetbrains, app:pieces os
